services:
  - type: web
    name: kiro-shop-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: BOT_TOKEN
        value: 8815350090:AAHcgEg8hp1tbGOjfGyIJq22VUa0ihCROXU
      - key: TRANZUPI_API_KEY
        value: 64c1cb9202d9646a0a75a7781decf3ee
      - key: ADMIN_USER_IDS
        value: "8568912134,8021345661"
      - key: TRANZUPI_UPI_ID
        value: paytm.s3h7hcx@pty
      - key: MERCHANT_NAME
        value: RAJ NARAYAN
